### PR TITLE
Proposal: Before and After pipe builder

### PR DESCRIPTION
**Pull request by jordond**
I recently got around to refactor my codebase to use the new `Interceptions.Builder` syntax.  And found that all my `pipe`'s that I use are `before` pipes, and with the new syntax I had to constantly type

```kotlin
...
// I Just want the `before` pipe.
on<SomeAction> {
  pipe(before = { ... }, after = {_, _ -> })
} 
```

So I created #107 so that I could do:

```kotlin
on<SomeAction> {
  pipe(before = { ... })
} 
```

But it would be nice to use kotlin's "outside the parentheses" lambda syntax

```kotlin
on<SomeAction> {
  beforePipe { state, action ->
     // do work
  }
}
```

So I created a `beforePipe`, and a `afterPipe`.

Note: this relies on #107

### CODE REVIEW

**Comment by etiennelenhart** [comment]
I like it. 🙂 Just wondering if `pipeBefore` and `pipeAfter` would be a bit more intuitive.

**Comment by jordond** [comment]
Done!

**Comment by etiennelenhart** [comment]
Just noticed that `pipeAfter` provides the nullable action type `T?`. Should probably also be changed to `T` and we're good to go.

**Comment by jordond** [comment]
Doh.. It's one of those days.

**Comment by etiennelenhart** [comment]
I guess that makes two of us. 😉

**Pull request merged**
